### ISSUE TITLE
Can this scripts be used for FastSurfer processed structural MRI data?

### ISSUE THREAD

**Issue by debinz** [reuter-lab/qatools-python#1]
Hi!

Thank you for developing this awesome tools, can this scripts be used for FastSurfer processed structural MRI data? Or is there any approach to do this?

Zeng

**Comment by kdiers** [comment]
Hi Zeng,

some minor modifications are needed; I am thinking of introducing a `--fastsurfer` switch. Maybe you can check back in a day or two, then we should have an update.

Best, Kersten
