### ISSUE TITLE
Screenshots module fails to select (default) slices when voxel size different than 1mm

### ISSUE THREAD

**Issue by dmartindeblas** [reuter-lab/qatools-python#11]
When using the screenshot option on subjects processed with FreeSurfer's recon-all including the -cm flag the module fails to create the screenshots (with the default views). We were looking into the code and it seems that the problem is that, when using the -cm flag, the voxel size of FreeSurfer outputs in not 1mm, and therefore in this line: 

https://github.com/Deep-MI/qatools-python/blob/580530b24f7f29cc1c7ab3f9211998493f49be7c/qatoolspython/createScreenshots.py#L220

the code fails to select volumetric data because there is no slice with those TkReg RAS coordinates.

As a workaround, we have tried to select the closest volumetric slice, but the there is a (slight) mismatch between the plotted surface and volumetric data. Therefore, it would be necessary either first check whether the selected "views" are feasible and if not change them to the closest feasible one for both surface and volumetric data, or interpolate volumetric data. We have some modifications to your code that performs the first option.

**Comment by kdiers** [comment]
Thank you @dmartindeblas, the detailed info and your suggestion is very helpful. I will take a look within the next days and try to solve the issue. If you want to, maybe create a pull request so that we can consider your modifications also. Thanks again.
