### ISSUE TITLE
Usability of qatools installed in python environment for non-programmers 

### ISSUE THREAD

**Issue by Dominic-Arold** [reuter-lab/qatools-python#14]
## Feature Description
Hello qatools Devs, thanks for providing this tool for the new Freesurfer versions! 

When installing the package in a python virtual environment, it would be convenient for my purpose to add an entry point in the setup.py which provides the same command-line functionality as the qatools.py in the cloned repo.
So after activating the environment instead writing a own script or e.g.
`python -c "from qatoolspython.qatoolspython import run_qatools; run_qatools(ouput_dir=..., )"`
a user can type
`qatools --output_dir= ...`

## Motivation
This would allow managing/using qatools as a python package while also providing the simplified command-line functionality of qatools.py to people with less programming experience (which is the typical use case in our lab).

I extended the latest version to include this functionality. So if you see are interested I can also open a pull request to make it more precise.

**Comment by kdiers** [comment]
Hi Dominic-Arold, thanks for your message and suggestion! Sounds like a good idea, so we'd certainly be interested in taking a look at this improvement. If you don't mind, please go ahead with opening a PR.

Best regards, Kersten

**Comment by kdiers** [comment]
Hi, 

thanks again for your contribution.

I've added it today, with one small change: it's merged into a newly created `freesurfer-module-dev` branch, which did not exist yet at the time of your pull request. Eventually, I will also merge it into the default `freesurfer-module-releases` branch. 

It seems that I had to push the additional changes from the `freesurfer-module-dev` branch into your `add-entry-point` branch to make the pull request work. So this is just to let you know about the changed status of your branch. Afterwards, I had to fix one issue withe `qatools_cmd.py` script to make it work with my other recent additions in the freesurfer-module-dev` branch. This fix (commit 16b2cb9) is not yet included in your branch, and calling the script will likely give an error if downloaded in its current form from your branch. So you may want to update your branch to the current status of the `freesurfer-module-dev` branch (or revert it to the previous state).

Sorry for the confusion, 

Kersten
