### ISSUE TITLE
qatools-python singularity integration

### ISSUE THREAD

**Issue by narloncassio** [reuter-lab/qatools-python#18]
## Question/Support Request

...
Dear experts, I was wondering if there's any way to integrate ```qatools-python``` installed on a cluster with an independent installation of FreeSurfer installed as a Singularity container? I understand there's a Docker container with both ```qatools-python``` and FreeSurfer v6 installed, however we wanted to use a different version of FreeSurfer (i.e., v 7.1.1.) which we have in a Singularity container.

Sorry if the question is confusing, happy to clarify further as needed.

**Comment by m-reuter** [comment]
Hi narloncassio, 
I don't think there is an easy way for this. Just use your FreeSurfer 711 container to process the images and our qatools+fs6 container to do the QA afterwards? The FS versions don't need to agree, we only call very few FS commands and are trying to get rid of them completely.
