### ISSUE TITLE
Check/Fix fastsurfer integration

### ISSUE THREAD

**Issue by m-reuter** [reuter-lab/qatools-python#19]
FastSurfer is about to release its first official version. For this release output file names have changed (e.g. we added DKT to files to highlight that the DKT atlas is used to define cortical segmentations). Please check if the QA tools still work, or if they need to be adopted to the new file names.

**Comment by alx080** [comment]
I also found 2 incorrectly labelled file names imo when using `--fastsurfer`,
in `qatoolspython.py` , there is no talairach.lta, only talairach.auto.xfm.lta e.g. and aparc+aseg.orig.mgz should be aparc+aseg.mgz as in FreeSurfer.

**Comment by kdiers** [comment]
Hi, and thanks for your report. Will change the aparc+aseg, but I am not sure that the `talairach.auto.xfm.lta` is used anywhere in either the current version of the qatools or FastSurfer output. If I am overlooking something, please let me know.

**Comment by m-reuter** [comment]
talairach.lta should be available now again in dev in the upcoming release. See https://github.com/Deep-MI/FastSurfer/pull/157  (it is a symbolic link to talairach.xfm.lta which is created also by FreeSurfer in version 7.2). 

And aparc+aseg.mgz will not exist, as we are using the more modern DKT atlas in FastSurfer, so look for the file aparc.DKTatlas+aseg.mgz .
