### ISSUE TITLE
Normal range for computed values

### ISSUE THREAD

**Issue by xjyang** [reuter-lab/qatools-python#2]
Hi,
After I ran the qatools for some Freesurfer subjects, I got some computed values such as Gray matter signal to noise ratio, Number of defects in the left hemisphere, and even some screen shots, etc. Do you have any document stating that what kind of values or screenshots should be considered to be bad quality in Freesurfer computing and thus needs human intervention?

John

**Comment by kdiers** [comment]
Hi John,

thanks for your message. We do not provide any cut-offs. I think that such values would be highly context-dependent, i.e. depend on the particular study/sample/population. Our general strategy is to look at outliers in the distributions of these values, and visually inspect the corresponding images to check if there are any issues that necessitate exclusion. The same is true for the screenshots, which are intended to allow for a quick survey of images, possibly prompting a more thorough inspection using freeview in suspicious cases. Hope this helps,

Kersten

**Comment by xjyang** [comment]
Thank you Kersten for the explanation!

I have a suggestion: if your QA tools can capture 3D images (DICOM, GIF
animation or even video) that show the segmentation results, that would be
great - much better than only showing one static image. From one image
(even though with different orientations) it's really hard to judge if the
segmentation is good or not.

Anyway, it's a very nice tool!

John

**Comment by m-reuter** [comment]
Hi Xiyang, 
You can of course always open the 3d results (like aseg.mgz or sparc+sarge.mgz on top of norm.mgz) if you want to look at the 3d results, for example with freeview.
Best Martin

**Comment by xjyang** [comment]
Thank you Martin!

John
