### ISSUE TITLE
Additional (inflated) surface views to match FS5 QA tool

### ISSUE THREAD

**Issue by Dominic-Arold** [reuter-lab/qatools-python#23]
Dear all,

as already brainstormed at the end of #[https://github.com/Deep-MI/qatools-python/issues/8] I would appreciate adding additional views to the (inflated) surface outputs. 

Concretely: Add bottom and medial views of left/right (inflated) surfaces. Maybe also add views with curvature overlay instead of parcellation. 

Reason: We currently aim to switch from the FS5 to this FS7 QA tool. It would be good that both tools allow a comparable output to ensure the same QA process. 

Is this already being implemented/discussed since the mentioned issue is still open? If not I am also happy to make a pull-request for the additional views of existing surfaces.

Kind regards,
Dominic

**Comment by kdiers** [comment]
Hi Dominic, thanks for your suggestion.

The views are currently fixed, but I think we could either add additional ones or make it configurable. If you want to, feel free to open a pull request. I will also be able to work on it and add this feature during next week.

Best regards, Kersten

**Comment by kdiers** [comment]
Hi Dominic, thanks for your suggestion.

The views are currently fixed, but I think we could either add additional ones or make it configurable. If you want to, feel free to open a pull request. I will also be able to work on it and add this feature during next week.

Best regards, Kersten

**Comment by Dominic-Arold** [comment]
Alright, I am on it.

**Comment by kdiers** [comment]
PR was merged.
