### ISSUE TITLE
Check skull stripping

### ISSUE THREAD

**Issue by ncbss** [reuter-lab/qatools-python#27]
Dear developers,

I wonder if there's a way to integrate a screenshots module for skull stripping in qatools-python? Would be great to visualize together with cortical segmentation if skull stripping worked as expected. I have some subjects where overagressing skull stepping removes brain tissue in the occipital lobe, but it's quite hard to detect that without overlaying the brainmaks.mgz onto the T1.mgz in Freeview.

Thank you for taking the time!

**Comment by kdiers** [comment]
Hi, and thanks for your suggestion. I guess this should be possible, so we'll try to implement it within the next 1-2 weeks.

**Comment by kdiers** [comment]
Hi again, we've added a `--skullstrip` / `--skullstrip-html` option to the toolbox. The README is also updated with some brief information about it. Please note that this option is currently only available in the [development branch] (https://github.com/Deep-MI/qatools-python/tree/freesurfer-module-dev), not the main branch. After cloning the repository, you may have to explicitly check out this branch to have it available `git checkout freesurfer-module-dev`. Let us know about any other suggestions or issues!
