### ISSUE TITLE
Screenshots in reversed left/right orientation

### ISSUE THREAD

**Issue by ncbss** [reuter-lab/qatools-python#28]
Hi there,
Thanks again for this incredible tool! Working with the developmental version of `qatools-python`, I noticed that the screenshots generated are showing outputs in reversed orientation in the x axis (left/right). This happens for both `screenshots` and ```skullstrip``` modules. I generated the screenshots for my data using the following code:

```
qatools-python/qatools.py \
        --subjects_dir /data \
        --output_dir /output \
        --screenshots \
        --skullstrip \
        --subjects subj-001 \
        --screenshots_views \
     x=60	x=57	x=54	x=51	x=48	x=45	x=42	x=39	x=36	x=33	x=30	x=27	x=24	x=21	x=18	x=15	x=12	x=9	x=6	x=3 \
     x=-3	x=-6	x=-9	x=-12	x=-15	x=-18	x=-21	x=-24	x=-27	x=-30	x=-33	x=-36	x=-39	x=-42	x=-45	x=-48	x=-51	x=-54	x=-57	x=-60 \
     y=60	y=57	y=54	y=51	y=48	y=45	y=42	y=39	y=36	y=33	y=30	y=27	y=24	y=21	y=18	y=15	y=12	y=9	y=6	y=3 \
     y=-3	y=-6	y=-9	y=-12	y=-15	y=-18	y=-21	y=-24	y=-27	y=-30	y=-33	y=-36	y=-39	y=-42	y=-45	y=-48	y=-51	y=-54	y=-57	y=-60 \
     z=60	z=57	z=54	z=51	z=48	z=45	z=42	z=39	z=36	z=33	z=30	z=27	z=24	z=21	z=18	z=15	z=12	z=9	z=6	z=3 \
     z=-3	z=-6	z=-9	z=-12	z=-15	z=-18	z=-21	z=-24	z=-27	z=-30	z=-33	z=-36	z=-39	z=-42	z=-45	z=-48	z=-51	z=-54	z=-57	z=-60 \
     --screenshots_layout 12 10
```

**Comment by kdiers** [comment]
Hello, and thanks for your feedback! We'll take a closer look and get back within the next few days. Cheers!

**Comment by kdiers** [comment]
Hello, and thanks again for your message. I probably have to ask for a clarification: the above command will generate a number of sagittal, coronal, and axial views. The x axis will be present in the coronal and axial views. Are you referring to these views regarding the reversed orientation? And what specifically do you mean by "reversed": reversed with regard to the FreeView convention (in this sense, the axis is indeed reversed)?

**Comment by ncbss** [comment]
Hi Kersten, thanks for the follow-up question. Yes, those are the views (axial and coronal), wherein what the screenshots module shows as the right side of the brain, it's shown as left side  in FreeView. See sample images below.

Thanks!

![sub-001_freeview_axial](https://user-images.githubusercontent.com/110060811/219822596-19c387ca-da89-45de-82fe-fa382b924161.png)



![sub-001_freeview_coronal](https://user-images.githubusercontent.com/110060811/219822601-5d58756b-74f0-4a1e-b2e6-09286045973b.png)



![sub-001_screenshot](https://user-images.githubusercontent.com/110060811/219822607-7acb1e29-930d-478e-8832-0ea80360833f.jpg)

**Comment by kdiers** [comment]
Hello, I have now added a `--screenshots_orientation <neurological|radiological>` argument. It allows to switch between left-is-left (neurological; default) and left-is-right (radiological; as in Freeview) orientation of the x axis in coronal and axial views. It is currently only included in the developmental [`freesurfer-module-dev`](https://github.com/Deep-MI/qatools-python/tree/freesurfer-module-dev) branch, but I expect that it will be introduced into the main branch within the next weeks, together with a major update of the main branch.

**Comment by m-reuter** [comment]
I am not sure we want to do this. Unless this is always(!) printed in the images, so that it is obvious what convention was used, I would only allow one convention (radiological). If someone really needs the other convention (e.g. for a publication) they can flip images themselves.

**Comment by m-reuter** [comment]
After discussion, we decided to switch to radiological (FreeSurfer and FastSurfer) convention in the next major release. To avoid confusion, there won't be an option to change this.
