### ISSUE TITLE
brainprintpython

### ISSUE THREAD

**Issue by slieped** [reuter-lab/qatools-python#3]
I have recently updated to the latest version version of qatools (git pull). 
When I try to include the --shape option, it returns the error that "**brainprintpython is not installed**".

I have already installed the BrainPrint-python and LaPy. In fact, I can import both packages without problem.

I have also checked the brainprint module, and I can not find the pyBrainPrint, which is loaded in the qatoolspython module.

If you need further information, I can try to provide as much as you need!
Thanks,

**Comment by m-reuter** [comment]
Sorry for the late reply. We will try to reproduce this. Also note that we are in the process of restructuring brainprint and lapy, and will fix this for the new versions.

**Comment by kdiers** [comment]
Thanks for your message. We have revised two dependencies (brainprint and lapy) of this package, and now the qatools-python package should work with the revised versions of these dependencies, including the --shape option.
