### ISSUE TITLE
Brainprint running twice?

### ISSUE THREAD

**Issue by robbwh** [reuter-lab/qatools-python#37]
I could be completely wrong, but it seems like brainprint is running a second time with identical arguments here

https://github.com/Deep-MI/qatools-python/blob/0089ba6e276ed9eea7a48e3ed9d64657b3b949c4/qatoolspython/qatoolspython.py#L1215

**Comment by kdiers** [comment]
Hello, and thanks for your report. Yes, that seems like a copy-and-paste error; we will correct that with the next update. Thanks again!
