### ISSUE TITLE
processing multiple subjects from a list of subject IDs saved in a text file

### ISSUE THREAD

**Issue by XinQi7788** [reuter-lab/qatools-python#4]
Can I use qatools-python to analysis FreeSurfer results on multiple subjects from a list of subject ID save in a text file?

Such as with a subjects flag as _--subjects subjectIDs.txt_

Inside the subjectIDs.txt 
sub1 sub2 sub3 ...

I tested it, but got error saying: ERROR: no subjects to process

Looking forward to your reply.  Thank you very much!

**Comment by kdiers** [comment]
Sorry, currently we only support to specify one or multiple FreeSurfer Subject IDs after the '--subjects' argument. Implementation and testing for the proposed functionality (specify subjects in a text file) could be done within approx. 1 week.

Best regards, Kersten

**Comment by XinQi7788** [comment]
Hi Kersten: Thanks for a quick reply! 

I will wait for testing its implementation later. 

Best Regards, Xin

**Comment by kdiers** [comment]
Hi, I've added the '--subjects-file <file>' option, which can be used as an alternative to the '--subjects <ID> [<ID> ...]' option. Inside the subjects file, there should be one ID per row. 

Best, Kersten

**Comment by XinQi7788** [comment]
Thank you very much.
Xin
