### ISSUE TITLE
Error installing fsqc via pip

### ISSUE THREAD

**Issue by RDoerfel** [reuter-lab/qatools-python#48]
## Description
I'm running into issues when installing `fsqc` via `pip `as described in the readme. 

## Steps to Reproduce
Steps to reproduce the observed behaviour, in as much detail as possible:
1. create and activate an empty conda environment with python: `conda create -n fsqc python`, `conda activate fsqc` 
2. Install `fsqc` via `pip`: `pip install fsqc`

## Error Message
I'm getting the following error:

> ERROR: Could not find a version that satisfies the requirement fsqc (from versions: none)
> ERROR: No matching distribution found for fsqc

## Expected Behavior
fsqc should be installed and accesible via cli and api

## Screenshots
<img width="458" alt="image" src="https://github.com/Deep-MI/fsqc/assets/40984141/3f459408-0a6f-4960-b0f5-aa8e6d55e961">

## Environment
 - qatools-python Version: 2.0 I suppose
 - OS: openSUSE Leap 15.4

**Comment by kdiers** [comment]
Thanks for the report, and sorry about that: the announcement about availability on pypi.org was a bit too early, but we are working on it and it should not take long. The same holds for dockerhub. I'll post an update when we're done. In the meantime, the GitHub install should still work.

**Comment by RDoerfel** [comment]
Great! installing via GihUb worked just fine :)

**Comment by kdiers** [comment]
The pip install should work now. Dockerhub might take a few more days, unfortunately.

**Comment by RDoerfel** [comment]
Yes, works nicely! Thanks for your work @kdiers
