### ISSUE TITLE
about generating cortical parcellation screen shots & html files with consolidated screen shots

### ISSUE THREAD

**Issue by XinQi7788** [reuter-lab/qatools-python#5]
Current version only creates screenshots of aseg file saved inside the screeshots folder within each subject's folder

1. Can cortical parcellation screenshots are created as well? How to do it?

2. Also in the old version https://surfer.nmr.mgh.harvard.edu/fswiki/QATools, a html file are created. 
Can a html file containing all the subjects' aseg screenshot and a html file containing all the subjects' cortical parcellation  screenshot are created?

Thank you very much.
Xin

**Comment by kdiers** [comment]
Hi Xin, 

we currently do not support the rendering of surface files (i.e. parcellation screenshots). For this purpose, we recommend using Freeview's scripting capabilities. See 'freeview -help' for documentation.

I've added a '--screenshots-html' option to generate an html overview page in the output directory, which can be used in addition to the '--screenshots' option. Use '--screenshots_layout 1 4' as an additional option to arrange 4 images per subject in a row. 

Hope this helps,

Kersten

**Comment by XinQi7788** [comment]
Thanks a lot.
Xin
