### ISSUE TITLE
Docker / singularity links are wrong in documentation

### ISSUE THREAD

**Issue by RDoerfel** [reuter-lab/qatools-python#52]
## Documentation
The documentation to build the [singularity ](https://github.com/Deep-MI/fsqc/blob/a409f6de16e2a99a9e46ed009d04ad5892143f49/singularity/Singularity.md?plain=1#L10) container leads to the wrong repository. I assume you want to point towards this one: [https://hub.docker.com/r/deepmi/fsqcdocker](https://hub.docker.com/r/deepmi/fsqcdocker). Hence:
`singularity build fsqc-latest.sif docker://deepmi/fsqc:latest` should become `singularity build fsqc-latest.sif docker://deepmi/fsqcdocker:latest`. Similar for all the following links referring to dockerhub. 

If you agree, I would be happy to open a PR to correct the documentation.

**Comment by kdiers** [comment]
Right, well spotted. Thanks for offering to correct this, please go ahead.
