### ISSUE TITLE
Outlier module not working with FastSurfer 2.2.0 output

### ISSUE THREAD

**Issue by acossa** [reuter-lab/qatools-python#54]
When using the `--outlier` and `--fastsurfer` flags, I get this error:

`Running outlier detection module ...

[ERROR: fsqcMain.py: 2278]: ERROR: outlier module failed
[ERROR: fsqcMain.py: 2279]: Reason: [Errno 2] No such file or directory: '/input/SUBJECT/stats/lh.aparc.stats'
[INFO: fsqcMain.py: 2288]: Done`

This is due to FastSurfer's output filename being "lh.aparc.DKTatlas.mapped.stats" but I would have expected the `--fastsurfer` to handle the different naming.

**Comment by kdiers** [comment]
Thanks for the report, we might have overlooked this. 

We'll review the code, and likely provide an update after testing.

**Comment by acossa** [comment]
Hi Kersten, 
Thank you so much for the prompt fix.
