### ISSUE TITLE
Add option to run subjects in parallel

### ISSUE THREAD

**Issue by costantinoai** [reuter-lab/qatools-python#57]
## Feature Description
Run subjects in parallel using multiple threads/cores
...

## Motivation
When a list of subjects is provided (e.g., no subjects id or multiple subjects ids are provided), the tool uses a single core to process the subjects sequentially. This make the computation time exponentially longer than it should be. An obvious alternative is to run concurrent processes (one per subject), but that is still not possible to do automatically since each subjects would overwrite the existing results (if the output folder is not explicitly set to a different one for each subjects).
...

## Alternatives
When a list of subjects is provided, each subject can be processed by a different core (or a small subset of subjects can be processed using all the cores) in order to significantly increase the computational power and reduce the time needed for processing. Tools like nypipe can be used to schedule tasks and assign them to specific resources.

**Comment by kdiers** [comment]
- Speeding up processing is certainly a good idea, especially for large datasets. At the moment, we'd probably recommend running several processes in parallel (i.e. the one-per-subject solution mentioned above). Also, this is probably the preferred way in conjunction with schedulers like SLURM or LSF that are typically present on servers, where parallelization has the greatest impact. Thanks for pointing out the issue that one might have with a common output directory in such a scenario: having a large number of subject-specific output directories instead is probably not the best solution, but I guess this whole issue can be solved with a distinction between individual- and group-level mode as suggested in #58.
- Building parallelization into the software itself is probably not so easy, and integration with nipype is likely a long-term project.

**Comment by kdiers** [comment]
Closing this issue because of the changes implemented in response to #56 and #58, which are expected also to help with this issue.
