### ISSUE TITLE
Add option to run the tool at the subject level or group level

### ISSUE THREAD

**Issue by costantinoai** [reuter-lab/qatools-python#58]
## Feature Description
It would be nice if the tool was able to process subjects independently, and then produce a group report. This group report could in principle show plots with outliers for each metric, and potentially even compare this with normative data (see mriqc).
...

## Motivation
At the moment, it is not possible to run the tool to produce a group report over pre-computed subjects' reports.
...

## Alternatives
The tools should be able to produce group reports from pre-computed subjects’ results (see mriqc).

**Comment by kdiers** [comment]
- Agreed, it makes sense to be able to run the tool in individual mode (creating subject-level results), group mode (collecting and summarizing results), or both. Currently, both individual- and group-level processing is done by default. However, being able to choose individual mode or group mode (or both) will also help with parallelizing computations (#57) and doing incremental processing (#56). We are currently considering to introduce `--no-group` and `--group-only` flags for this purpose.
- Producing summary reports is not the highest priority currently, but may be a long-term goal; for the moment, our focus is on providing tables / images, and leaving subsequent processing / visualization to the users.

**Comment by kdiers** [comment]
`--no-group` and `group-only` processing options have been implemented now and have undergone initial testing. They are part of the development version currently (`dev` branch), which may still change, and will be part of the next release of the software after further testing; likely in July. Closing this issue now, feel free to reopen in case of any issues.
