### ISSUE TITLE
Push more recent version of the fsqc tools to dockerhub?

### ISSUE THREAD

**Issue by flok-dev** [reuter-lab/qatools-python#68]
## Question/Support Request

Dear Deep-MI team,

As far as I can see, the latest version of the FSQC tools pushed to docker hub seems to be v2.0.0. For ease of use, it would be greatly appreciated if you could push more recent versions of the FSQC tools to docker hub.

Thanks for your consideration!

**Comment by kdiers** [comment]
Hello, thanks for the reminder :slightly_smiling_face: We have now pushed the most recent version.
