### ISSUE TITLE
A problem occurred with the surface overlays

### ISSUE THREAD

**Issue by XinQi7788** [reuter-lab/qatools-python#7]
Hi

Another error occurs while running the command like below. This time without "--shape" flag .
The error shows as: "A problem occurred with the surface overlays"... the command window freeze there forever.

It is not just one subject image, it happens on multiple cases as well.

Here is the command like below. 

python qatools.py --subjects_dir /FreeSurferResultsFolder 
--output_dir /Exp2_Oct06-2021 
--subjects-file /listSubjectID_complete.txt
--screenshots 
--screenshots_layout 1 4 
--screenshots-html 
 --fornix 
--outlier

**Comment by XinQi7788** [comment]
The same issue of "A problem occurred with the surfer overlays" , **that makes the terminal frozen and NO files of qatools-result.html and qatools-results.csv are created** although the flags of --screenshots-html --outlier are used.

**Comment by kdiers** [comment]
Thanks for the info! I have to admit that I had trouble replicating this issue, even with the same images, and trying both on a MacBook and a Ubuntu machine. If you have any further info, please let me know, I am happy to take another look.

**Comment by XinQi7788** [comment]
Hi Kersten:

I am using the latest updated qatools-python, but encountered the same "a problem occurred with the surface overlays" issue while running some ANDI T1w images on a ubuntu machine.

When I noticed the "A problem occurred with the surface overlays" message, I clicked Control + C, then clicked Enter, the program kept running the rest of list of images.

***@***.***

Here are examples of image lists make the Linux terminal froze while running qatools-python.
ADNI_011_S_0022_I32389
ADNI_033_S_0739_I119135
ADNI_035_S_4082_I296308

Can you please share a link that I can upload FreeSurfer results of those images?

Looking forward to your reply

Xin

From: Kersten Diers ***@***.***>
Sent: Wednesday, October 13, 2021 4:44 AM
To: Deep-MI/qatools-python ***@***.***>
Cc: Xin Qi ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Deep-MI/qatools-python] A problem occurred with the surface overlays (#7)


Thanks for the info! I have to admit that I had trouble replicating this issue, even with the same images, and trying both on a MacBook and a Ubuntu machine. If you have any further info, please let me know, I am happy to take another look.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDeep-MI%2Fqatools-python%2Fissues%2F7%23issuecomment-942071486&data=04%7C01%7Cxin_qi%40eisai.com%7Ceadf58d20ec7425e867108d98e25a5fb%7C013327ea41e944308dfacbb90ba7b1fa%7C0%7C0%7C637697114617454650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U4AsRilgYDNpFAtpJye7%2BqJP4dWXZe%2BfD65SSs9xGbA%3D&reserved=0>, or unsubscribe<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASMEXYPGMGSHKYW3GBSK3DLUGVBGBANCNFSM5FNFGZUQ&data=04%7C01%7Cxin_qi%40eisai.com%7Ceadf58d20ec7425e867108d98e25a5fb%7C013327ea41e944308dfacbb90ba7b1fa%7C0%7C0%7C637697114617464605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4rb1vrGRvpG3zQ%2BH0vQjahxLcnArHvyDOZmASxMJ7Qg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cxin_qi%40eisai.com%7Ceadf58d20ec7425e867108d98e25a5fb%7C013327ea41e944308dfacbb90ba7b1fa%7C0%7C0%7C637697114617474564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xHzhUe6l4JVBKB%2F4eJFupq9UQ2sHiplAXCR24AGaZnY%3D&reserved=0> or Android<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cxin_qi%40eisai.com%7Ceadf58d20ec7425e867108d98e25a5fb%7C013327ea41e944308dfacbb90ba7b1fa%7C0%7C0%7C637697114617474564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=alHmwuwCs0xrwg%2By2ShRknX5Ts9t6jUHhPUOgqOVwY4%3D&reserved=0>.


[This e-mail message may contain privileged, confidential and/or proprietary information of Eisai. If you believe that it has been sent to you in error, please contact the sender immediately and delete the message including any attachments, without copying, using, or distributing any of the information contained therein. This e-mail message should not be interpreted to include a digital or electronic signature that can be used to authenticate an agreement, contract or other legal document, nor to reflect an intention to be bound to any legally-binding agreement or contract.]

**Comment by XinQi7788** [comment]
Hi Kersten:

I am using the latest updated qatools-python, but encountered the same “a problem occurred with the surface overlays” issue while running some ANDI T1w images on a ubuntu machine.  

When I noticed the “A problem occurred with the surface overlays” message, I clicked Control + C, then clicked Enter, the program kept running the rest of list of images. 


Here are examples of image lists make the Linux terminal froze while running qatools-python. 
**ADNI_011_S_0022_I32389
ADNI_033_S_0739_I119135
ADNI_035_S_4082_I296308**

Can you please share a link that I can upload FreeSurfer results of those images? 

Looking forward to your reply

Xin
